In [14]:
import torch

a = torch.FloatTensor([[1,2],[3,4]])
b = torch.FloatTensor([[2,2],[3,3]])
a.mul_(b)
print(a)
print(a.shape)
print(a.device)
print(a.dtype)
print(a.sum(dim=0))
print(a.sum(dim=-1))
t1 = torch.zeros(2,3)
print(t1)
t2 = torch.arange(4)
print(t2)
t3 = torch.rand(3)
print(t3)

tensor([[ 2.,  4.],
        [ 9., 12.]])
torch.Size([2, 2])
cpu
torch.float32
tensor([11., 16.])
tensor([ 6., 21.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0, 1, 2, 3])
tensor([0.1749, 0.7438, 0.2233])


In [15]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
t1_gpu = t1.to(device)
print(t1_gpu.device)

cpu


In [22]:
t2 = torch.arange(6)
t2_reshape = t2.reshape(3,2)
print(t2_reshape)
t2_squeeze = t2.reshape(2,1,3)
print(t2_squeeze)
t2_permute = t2_reshape.permute(1,0)
print(t2_permute)

tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[[0, 1, 2]],

        [[3, 4, 5]]])
tensor([[0, 2, 4],
        [1, 3, 5]])


In [32]:
t1 = torch.FloatTensor([[0,1,2],[3,4,5]])
t2 = torch.FloatTensor([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

t2 = t2.transpose(0,1)
print(t1.shape, t2.shape)

t33 = t1 @ t2
print(t3,t3.shape)

torch.Size([2, 3]) torch.Size([3, 4])
tensor([[  5.,  14.,  23.,  32.],
        [ 14.,  50.,  86., 122.]]) torch.Size([2, 4])


In [33]:
row_argmax = torch.argmax(t33,dim=0)
print(row_argmax)
col_argmax = torch.argmax(t33,dim=-1)
print(col_argmax)

tensor([1, 1, 1, 1])
tensor([3, 3])


In [41]:
t11 = torch.stack([t1,t1],dim=0)
t112 = torch.stack([t1,t1],dim=-1)
t111 = torch.cat([t1,t1],dim=0)

print(t11,"\n",t112)
print(t111)

tensor([[[0., 1., 2.],
         [3., 4., 5.]],

        [[0., 1., 2.],
         [3., 4., 5.]]]) 
 tensor([[[0., 0.],
         [1., 1.],
         [2., 2.]],

        [[3., 3.],
         [4., 4.],
         [5., 5.]]])
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [0., 1., 2.],
        [3., 4., 5.]])


In [43]:
import torch 
import torch.nn.functional as F

x = torch.ones(7)
y = torch.zeros(3)

w1 = torch.randn(7,5,requires_grad=True)
b1 = torch.randn(5,requires_grad=True)
w2 = torch.randn(5,3,requires_grad=True)
b2 = torch.randn(3,requires_grad=True)

z1 = x@w1+b1
z2 = F.relu(z1)
z3 = z2@w2+b2
#calcylate loss
loss = F.binary_cross_entropy_with_logits(z3,y)
#backpropagation
loss.backward()
print(w1.grad)
print(b1.grad)
print(w2.grad)
print(b2.grad)


tensor([[ 0.0000,  0.0000, -0.1367,  0.9866,  0.0637],
        [ 0.0000,  0.0000, -0.1367,  0.9866,  0.0637],
        [ 0.0000,  0.0000, -0.1367,  0.9866,  0.0637],
        [ 0.0000,  0.0000, -0.1367,  0.9866,  0.0637],
        [ 0.0000,  0.0000, -0.1367,  0.9866,  0.0637],
        [ 0.0000,  0.0000, -0.1367,  0.9866,  0.0637],
        [ 0.0000,  0.0000, -0.1367,  0.9866,  0.0637]])
tensor([ 0.0000,  0.0000, -0.1367,  0.9866,  0.0637])
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [9.9751e-01, 9.3588e-01, 5.4297e-06],
        [9.9854e-01, 9.3685e-01, 5.4353e-06],
        [1.3688e+00, 1.2842e+00, 7.4505e-06]])
tensor([3.2926e-01, 3.0892e-01, 1.7923e-06])


In [47]:
from torch.utils.data import Dataset, DataLoader
import csv

class SimpleDataset(Dataset):
    def __init__(self,csv_file = None,root_dir=None):#가져오는 파일에 따라 다르게 설정
        with open(csv_file) as file:
            self.annotations = file.readlines()
        self.root_dir = root_dir
    def __getitem__(self,idx):
        x_path,y = self.annotations[idx]
        x = self.read(x_path)
        return x,y
    def __len__(self):
        return len(self.annotations)
    def read(self,x_path):
        return x_path
    
def my_collate_fn(data):#각기 다른 배치사이즈로 샘플을 만들고 나서 빈칸을 0으로 패딩해주는 과정
        max_len =10
        batch = []
        for x,y in data:
            x_padded = torch.cat([x,torch.zeros(max_len-x.shape[0])])
            batch.append(x_padded)
        return torch.stack(batch, dim=0)
   
dataset = SimpleDataset()
dataLoader = DataLoader(dataset,batch_size=16,collate_fn=my_collate_fn,shuffle=True)
#수정필요함

TypeError: expected str, bytes or os.PathLike object, not NoneType

In [ ]:
def train(model, scheduler, optim, loss_fn, train_loader, epochs, device):
    for epoch in range(epochs):
        train_loss = 0.0
        model.train()
        for batch in train_loader:
            optim.zero_grad()
            input, target = batch_size
            input = input.to(device)
            target = target.to(device)
            output = model(input)
            loss = loss_fn(output,target)
            loss.backward()
            optim.step()
            train_loss += loss.detach().item()
        scheduler.step()
        train_loss /= len(train_loader.dataset)
        print(f"Epoch: {epoch+1},Trainning Loss : {train_loss}")
import torch.optim as optim
import torch.nn as nn
optimizer = optim.SGD(model.parameters(),lr=1e-2,momentum=0.9)
scheduler = optim.lr_scheduler.ExponentialLR(optimizer,gmma=0.9)
model.to(device)

train(model, scheduler, optim, nn.CrossEntropyLoss(), train_loader, num_epochs, device)
