In [4]:

l = [1,2,3,4,5,6,7,8,9]
w = [9,8,7,6,5,4,3,2,1]
fish_data = [[l,w] for l,w in zip(l,w)]#zip함수는 나열된 리스트에서 원소를 하나씩 뽑는다
print(fish_data)
fish_target = [1]*5+ [0]*4

[[1, 9], [2, 8], [3, 7], [4, 6], [5, 5], [6, 4], [7, 3], [8, 2], [9, 1]]


In [5]:
from sklearn.neighbors import KNeighborsClassifier

kn =KNeighborsClassifier()
kn.fit (fish_data,fish_target)
kn.score(fish_data,fish_target)#알아서 predict를 수행해서 예측점수를 알려준다 여기서는 score할 것과 fit에 들어간 값들이 일치하므로 100점이다

#classifier할 개체를 0과1로 나누어 놓고 fit and score 한 것이다.
#fish_target 은 classify 할 객체
#fish_data는 fish의 정보

1.0

In [6]:
#이제 훈련세트와 트레이닝 세트로 나누어서 진짜로 모델이 어느정도 예측을 하는지 측정한다
#data_slicing
train_input = fish_data[:5]
test_input = fish_data[5:9]

train_output = fish_target[:5]
test_output = fish_target[5:9]

kn.fit (train_input,train_output)
kn.score(test_input,test_output)

0.0

In [8]:
#numpy의 사용
import numpy as np

input_array = np.array(fish_data)
output_array = np.array(fish_target)

print(input_array)
print(input_array.shape)# shape 는 샘플수, 특성수 로 나온다
print(input_array.sum)

[[1 9]
 [2 8]
 [3 7]
 [4 6]
 [5 5]
 [6 4]
 [7 3]
 [8 2]
 [9 1]]
(9, 2)
<built-in method sum of numpy.ndarray object at 0x00000221EA43ACF0>


In [13]:
np.random.seed(42)
index = np.arange(8)# 0부터9번 인덱스까지 증가하는 배열을 만든다
np.random.shuffle(index)# 그 배열을 무작위로 섞는다

train_input = input_array[index[:4]] #shuffle 된 숫자로 인덱스
test_input = input_array[index[5:9]] #shuffle 된 숫자로 인덱스
# 여기서 중요한건 input_array로는 이렇게 넣을 수 있다는 것
# fish_data는 이렇게 못 나눈다

In [18]:
#튜플은 리스트와 비슷한데 원소에 순서가 있지만 수정할 수 없다.
fish_data = np.column_stack((l,w)) # ㅣ과 w를 각각 행으로 쭉 세우고 열로 더헤서 만든 데이터
print(fish_data)

[[1 9]
 [2 8]
 [3 7]
 [4 6]
 [5 5]
 [6 4]
 [7 3]
 [8 2]
 [9 1]]


In [20]:
fish_target = np.concatenate((np.ones(4),np.zeros(5)))
data  = np.column_stack((fish_data,fish_target))
print(data)
# 아래는 그냥 해본것이고 data 와 target을 나누어야 하므로 0과1을 data에 더하지는 않는다

[[1. 9. 1.]
 [2. 8. 1.]
 [3. 7. 1.]
 [4. 6. 1.]
 [5. 5. 0.]
 [6. 4. 0.]
 [7. 3. 0.]
 [8. 2. 0.]
 [9. 1. 0.]]
